FROM node:22.23.1-alpine

ENV NODE_ENV=development

WORKDIR /app

RUN addgroup -S angular \
    && adduser -S angular -G angular

COPY package.json package-lock.json ./
COPY angular.json tsconfig.json tsconfig.app.json ./
COPY proxy.conf.docker.json ./

COPY src ./src

RUN npm ci \
    && npm cache clean --force \
    && chown -R angular:angular /app

USER angular

EXPOSE 4200

CMD ["npm", "run", "start:docker"]