# syntax=docker/dockerfile:1

FROM node:22.23.1-alpine

ENV NODE_ENV=development

WORKDIR /app

RUN addgroup -S academico \
    && adduser -S academico -G academico

COPY package.json package-lock.json ./

RUN npm ci \
    && npm cache clean --force \
    && chown -R academico:academico /app

USER academico

EXPOSE 3000


# syntax=docker/dockerfile:1

FROM node:22.23.1-alpine

ENV NODE_ENV=development

WORKDIR /app

RUN addgroup -S academico \
    && adduser -S academico -G academico

COPY package.json package-lock.json ./

RUN npm ci \
    && npm cache clean --force \
    && chown -R academico:academico /app

USER academico

EXPOSE 3000


CMD ["npm", "run", "start:dev"]